name: build_size
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  report-size:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn && cd site && yarn && cd ..

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: report-compressed-size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          build-script: 'prepublishOnly'
          pattern: './{dist,es,lib,icon}/**/*.{js,css}'
          clean-script: 'dependencies'

      - name: build:cjs
        run: yarn run build:cjs
